import sys

import lsst_sphinx_bootstrap_theme


# Work around Sphinx bug related to large and highly-nested source files
sys.setrecursionlimit(2000)

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'documenteer.sphinxext'
]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Services'
copyright = '2020 Association of Universities for Research in Astronomy (AURA), Inc.'
author = 'Rubin Observatory'

version = 'Current'
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    '_build',
    'README.rst',
    '.venv',
    'venv',
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# The reST default role cross-links Python (used for this markup: `text`)
default_role = 'py:obj'

# Intersphinx

intersphinx_mapping = {
    # 'python': ('https://docs.python.org/3/', None),
}

rst_epilog = """

.. |roundtable-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=roundtable
   :target: https://cd.roundtable.lsst.codes/applications/roundtable
   :alt: Roundtable app status

.. |roundtable-security-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=security
   :target: https://cd.roundtable.lsst.codes/applications/security
   :alt: Security app status

.. |roundtable-argo-cd-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=argo-cd
   :target: https://cd.roundtable.lsst.codes/applications/argo-cd
   :alt: Argo CD app status

.. |roundtable-nginx-ingress-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=nginx-ingress
   :target: https://cd.roundtable.lsst.codes/applications/nginx-ingress
   :alt: nginx-ingress app status

.. |roundtable-cert-manager-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=cert-manager
   :target: https://cd.roundtable.lsst.codes/applications/cert-manager
   :alt: cert-manager app status

.. |roundtable-prometheus-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=prometheus
   :target: https://cd.roundtable.lsst.codes/applications/prometheus
   :alt: Prometheus app status

.. |roundtable-strimzi-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=strimzi
   :target: https://cd.roundtable.lsst.codes/applications/strimzi
   :alt: Strimzi app status

.. |roundable-events-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=events
   :target: https://cd.roundtable.lsst.codes/applications/events
   :alt: Events app status

.. |roundtable-app-land-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=app-land
   :target: https://cd.roundtable.lsst.codes/applications/app-land
   :alt: App Land app status

.. |roundtable-sealed-secrets-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=sealed-secrets
   :target: https://cd.roundtable.lsst.codes/applications/sealed-secrets
   :alt: Sealed Secrets app status

.. |roundtable-vault-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=vault
   :target: https://cd.roundtable.lsst.codes/applications/vault
   :alt: Vault app status

.. |roundtable-vault-secrets-operator-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=vault-secrets-operator
   :target: https://cd.roundtable.lsst.codes/applications/vault-secrets-operator
   :alt: Vault Secrets Operator app status

.. |roundtable-logging-status| image:: https://cd.roundtable.lsst.codes/api/badge?name=logging
   :target: https://cd.roundtable.lsst.codes/applications/logging
   :alt: Logging app status
"""

# -- Options for linkcheck builder ----------------------------------------

linkcheck_retries = 2
linkcheck_timeout = 5  # seconds
linkcheck_ignore = [
    r'^https://console.cloud.google.com',
    r'^https://cd.roundtable.lsst.codes',
    r'^https://monitoring.roundtable.lsst.codes',
    r'^http://localhost',
]

# -- Options for HTML output ----------------------------------------------

templates_path = [
    '_templates',
    lsst_sphinx_bootstrap_theme.get_html_templates_path()
]

html_theme = 'lsst_sphinx_bootstrap_theme'
html_theme_path = [lsst_sphinx_bootstrap_theme.get_html_theme_path()]


html_context = {
    # Enable "Edit in GitHub" link
    'display_github': True,
    # https://{{ github_host|default("github.com") }}/{{ github_user }}/
    #     {{ github_repo }}/blob/
    #     {{ github_version }}{{ conf_py_path }}{{ pagename }}{{ suffix }}
    'github_user': 'lsst-sqre',
    'github_repo': 'roundtable',
    'conf_py_path': '',
    # TRAVIS_BRANCH is available in CI, but master is a safe default
    'github_version': 'master' + '/'
}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {'logotext': project}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = project

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = project

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False
